### ISSUE TITLE
Why not make Pieces, Squares, etc. instances of Show Typeclass?

### ISSUE THREAD

**Issue by dfornika** [haskelllive/haskelllive#3]
I'm curious why you decided to create functions called showPiece and showSquare, rather than defining a show function for the Piece and Square types:

```
instance Show Piece where
  show = ...
```

**Comment by reinh** [comment]
Essentially, two reasons:

First, because `Show` is used to inspect a Haskell value so I prefer to derive it as much as possible so that it shows uniformly to other derived instances. `show*` and `read*` will be used for interaction. I guess I could have called them pieceToChar or charToPiece but that's boring.

Second, because `show` and `read` are not very performant.

**Comment by dfornika** [comment]
Ok, I suppose the first point will make more sense as the program develops more.  I'm not sure I understand your second point.  Would the performance of `showPiece` change if it were simply moved into the definition of `show` inside the instance declaration for `Show Piece`?

In any case, I'm looking forward to seeing how the program develops.  Keep up the good work!

**Comment by reinh** [comment]
@dfornika while show is fine, read is slow and difficult to define. If we're going to define show in terms of showPiece then we would want to define read in terms of readPiece, but doing so is non-trivial as we have to operate on strings rather than characters, and is beyond the scope of a introductory Haskell video. Using `showPiece` and `readPiece` lets me neatly avoid the whole issue.

Also, show and read are really intended for debugging use, not for IO interaction.

**Comment by reinh** [comment]
@dfornika `show` is rather slow as well btw: http://www.randomhacks.net/articles/2007/01/22/high-performance-haskell. That's really String overhead but not using showPiece to implement show for Piece lets us replace with a ByteString if necessary.

**Comment by paulcc** [comment]
Not sure I agree with a few points here. I'd be tempted to use show and read right away, and optimise later if it actually does turn out to be a problem. ("Premature optimization is ..."). Also be prepared to trust the compiler to add some magic. It's also a shame to miss out on the overloading too. 

Show doesn't have to be for debugging either. It's unfortunate that GHCi doesn't seem to have the +u flag that Hugs has (which uses the internal default show code rather than the declared Show instances). Though as an alternative how about  another class which provides an overloaded .inspect method in the Ruby style? There may even be a library for it already (something like Serialize?)

**Comment by reinh** [comment]
@paulcc Good points, but `read` is defined through a rather arcane parsing interface that I had hoped to avoid.
